function Download() {
    const handleDownload = () => {
        const content = "This is some text generated by the application.";
        const blob = new Blob([content], { type: 'text/plain' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'generated-file.txt';
        link.click();
    };

    return (
        <div className="flex flex-col justify-center items-center h-screen w-screen bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 text-white p-8">
            <h1 className="text-center text-4xl font-extrabold mb-4 animate-fade-in"></h1>
            <h1 className="text-5xl font-bold mb-6 text-white">Download Your Voice Bank</h1>
            <p className="text-lg mb-10 text-center max-w-lg">
                Congrats on recording your very own voice bank!
            </p>
            <div className="flex items-center justify-center mb-10">
                <div className="animate-bounce bg-indigo-500 p-6 rounded-full shadow-md">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                </div>
            </div>
            <button 
                className="bg-white text-indigo-600 px-8 py-3 rounded-full font-semibold shadow-lg hover:bg-indigo-200 transform transition hover:scale-105 duration-300"
                onClick={handleDownload}
            >
                Download Your File
            </button>
        </div>
    );
}

export default Download;